import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1784642424911 implements MigrationInterface {
    name = 'Default1784642424911'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "FK_eb1658fc6adde4c67c2e6ac3a47"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "FK_6aae5fece0741ba004c922ebacb"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "FK_b59117532f98fc4e4e3c558d365"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "FK_7c46626609a2fa17bfc6f49d9dd"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "FK_a1f66b99dd471cf095b6803e0d7"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "FK_136d00713f5cc9daef5a5df6cc8"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "FK_0c3e2ba4eac1a23f6b5013349a9"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP CONSTRAINT "FK_3c63dfaf4590b751af96d12f853"`);
        await queryRunner.query(`ALTER TABLE "cidades" DROP CONSTRAINT "FK_26fdc1287cd3546d3445ae61fab"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_e5dc50dc3a19a78ba3d6aa8df59"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP CONSTRAINT "FK_ca615f9bb29f30e88403e10d15d"`);
        await queryRunner.query(`ALTER TABLE "exames" DROP CONSTRAINT "FK_5416bbb44a12e2b5f89a1826b47"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP CONSTRAINT "FK_9a16946211d04cc3ef1409e3074"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP CONSTRAINT "FK_fc0e9dfe46f90c7b86fd9645383"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP CONSTRAINT "FK_b50000f3706608bec4ef0c925c0"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP CONSTRAINT "FK_017442fdf85248269ab2e248ebc"`);
        await queryRunner.query(`ALTER TABLE "cidades" RENAME COLUMN "estados_idEstado" TO "idEstado"`);
        await queryRunner.query(`ALTER TABLE "exames" RENAME COLUMN "pacientes_idPaciente" TO "idGestacao"`);
        await queryRunner.query(`CREATE TABLE "consultasAbertura" ("id" SERIAL NOT NULL, "abortos" integer NOT NULL, "natimortos" integer NOT NULL, "nivelRisco" boolean NOT NULL, "dataUltimaMenstruacao" TIMESTAMP NOT NULL, "idadeGestacional" integer NOT NULL, "comorbidades" text, "prescricaoExames" text, "prescricaoPreventivos" text, "sintomas" text, "observacoes" text, "status" boolean NOT NULL, "dataCriacao" TIMESTAMP NOT NULL DEFAULT now(), "dataAlteracao" TIMESTAMP DEFAULT now(), "idGestacao" integer, "idAgendamento" integer, "idProfissional" integer, "idAfericaoGestante" integer, CONSTRAINT "REL_c06fe4220bc31e20b9d062c158" UNIQUE ("idGestacao"), CONSTRAINT "REL_d8034b1478f5fa22932ae267ca" UNIQUE ("idAgendamento"), CONSTRAINT "REL_d6e6bd8a56b543d986f80d1902" UNIQUE ("idAfericaoGestante"), CONSTRAINT "PK_41dac31304020c6b97dde3a03ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "afericoesGestante" ("id" SERIAL NOT NULL, "glicose" integer NOT NULL, "peso" integer NOT NULL, "pressaoArterial" integer NOT NULL, "alturaUterina" integer NOT NULL, "batimentosCardiacos" integer NOT NULL, "edemas" boolean NOT NULL, "movimentosFetais" boolean NOT NULL, "avaliacaoEdemas" text, CONSTRAINT "PK_5806807cb91282073987dd925a0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "areaCobertura" ("id" SERIAL NOT NULL, "identificacao" character varying NOT NULL, "qtdPacientes" integer NOT NULL, "status" boolean NOT NULL, CONSTRAINT "PK_5ed0a30aa7db6335d7405d5d57e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contatos" ("id" SERIAL NOT NULL, "titular" boolean NOT NULL, "email" character varying, "telefonePrincipal" character varying NOT NULL, "telefoneSecundario" character varying, "idPessoa" integer, "idResponsavel" integer, CONSTRAINT "PK_994cdcb2c56dfb5b66217c854cc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "afericoesBebes" ("id" SERIAL NOT NULL, "risco" boolean NOT NULL, "altura" integer NOT NULL, "peso" integer NOT NULL, "cranioCefalico" integer NOT NULL, "testeApgar" integer NOT NULL, CONSTRAINT "PK_6a7b0147a996235fd24ab968581" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "visitaRecemNascido" ("id" SERIAL NOT NULL, "tipoAmamentacao" character varying NOT NULL, "prescricaoTestes" text, "prescricaoVacinas" text, "saudeUmbigo" boolean NOT NULL, "observacoes" text, "status" boolean NOT NULL, "dataCriacao" TIMESTAMP NOT NULL DEFAULT now(), "dataAlteracao" TIMESTAMP DEFAULT now(), "idAgendamento" integer, "idBebe" integer, "idAfericaoBebe" integer, "idProfissionais" integer, CONSTRAINT "REL_52140c874ac3ab8f13366c071c" UNIQUE ("idAgendamento"), CONSTRAINT "REL_a85d8f2fa353aae051b8e6af1d" UNIQUE ("idBebe"), CONSTRAINT "REL_0fdca7f509d4325c331332d983" UNIQUE ("idAfericaoBebe"), CONSTRAINT "PK_fa77077a1ce3ab724d67da7a8d5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "agendamentos_idAgendamento"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "pacientes_idPacientes"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "profissionais_idProfissionais"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "faseAcompanhamento"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "observacao"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "alturaUterina"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "batimentosCardiacos"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "REL_7c46626609a2fa17bfc6f49d9d"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "consultas_id"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "historicoGestacional"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "dataCriacao"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "dataAlteracao"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "agendamentos_idAgendamento"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "pacientes_idPaciente"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "profissionais_idProfissional"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP COLUMN "equipes_idEquipe"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP COLUMN "funcao"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP COLUMN "observacao"`);
        await queryRunner.query(`ALTER TABLE "responsaveis" DROP COLUMN "telefone"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP COLUMN "cidades_idCidade"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "email"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "telefone"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "tipoSanguineo"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "comorbidades"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "alergias"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "profissao"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "responsavel"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "examesId"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "nivelRisco"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "observacao"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "dataCriacao"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "dataAlteracao"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "pacientes_idPaciente"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "profissionais_idProfissional"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "idadeGestacional"`);
        await queryRunner.query(`ALTER TABLE "gestacoes" DROP COLUMN "dataUltimaMenstruacao"`);
        await queryRunner.query(`ALTER TABLE "gestacoes" DROP COLUMN "dataProvavelParto"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "pesoNascimento"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "comprimentoNascimento"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "apgar"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "primeiraConsulta"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP CONSTRAINT "REL_b50000f3706608bec4ef0c925c"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "pessoas_idPessoa"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "gestacoes_idGestacao"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "observacoes"`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "ultimaConsultaRealizada" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "movimentosFetais" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "vulnerabilidades" text`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "observacoes" text`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "recomendacoes" text`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "idAgendamento" integer`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "UQ_c57978982b4e0638aaea0e0fe2f" UNIQUE ("idAgendamento")`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "idGestacao" integer`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "idProfissionais" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "nivelRisco" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "status" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "sintomas" text`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "observacoes" text`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "dataCriacao" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "dataAlteracao" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "idGestacao" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "idAgendamento" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "UQ_52cfb62ef98cd012d176d7fa46f" UNIQUE ("idAgendamento")`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "idProfissional" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "idAfericaoGestante" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "UQ_af30f71f9bf51c20d3840f5f73a" UNIQUE ("idAfericaoGestante")`);
        await queryRunner.query(`ALTER TABLE "agendamentos" ADD "dataExclusao" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "prescricoes" text`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "idAgendamento" integer`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "UQ_a989d78546c4c92a75030f9e57b" UNIQUE ("idAgendamento")`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "idGestacao" integer`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "idProfissional" integer`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD "cargo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD "equipe" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD "idAreaCobertura" integer`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD CONSTRAINT "UQ_77e4ac50f879d85bc90d34c7cea" UNIQUE ("idAreaCobertura")`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD "titular" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD "idPessoa" integer`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD "idResponsavel" integer`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD "idCidade" integer`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "tipoPessoa" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "hasResponsavel" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "tipoSanguineo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "alergias" character varying`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "nome" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "idGestacao" integer`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "idBebe" integer`);
        await queryRunner.query(`ALTER TABLE "gestacoes" ADD "nivelRisco" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gestacoes" ADD "idadeGestacional" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "nome" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "dataExclusao" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "idGestacao" integer`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "pressaoArterial"`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "pressaoArterial" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "idadeGestacional"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "idadeGestacional" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agendamentos" ALTER COLUMN "dataRetorno" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agendamentos" ALTER COLUMN "horaRetorno" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD CONSTRAINT "UQ_0cdb0a19a284ab273d794bce3a5" UNIQUE ("matricula")`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "tipoPaciente"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "tipoPaciente" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "FK_c57978982b4e0638aaea0e0fe2f" FOREIGN KEY ("idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "FK_3a4ce6bcb3c0b621ec0cc9cb93c" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "FK_6c4a5500dfbc4d941da6885e4cf" FOREIGN KEY ("idProfissionais") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" ADD CONSTRAINT "FK_c06fe4220bc31e20b9d062c158b" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" ADD CONSTRAINT "FK_d8034b1478f5fa22932ae267cab" FOREIGN KEY ("idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" ADD CONSTRAINT "FK_0b6fc12b539c1f5d10cecca9176" FOREIGN KEY ("idProfissional") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" ADD CONSTRAINT "FK_d6e6bd8a56b543d986f80d1902a" FOREIGN KEY ("idAfericaoGestante") REFERENCES "afericoesGestante"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "FK_e5071a3dcca98ed5006c2cba34c" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "FK_52cfb62ef98cd012d176d7fa46f" FOREIGN KEY ("idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "FK_97b0493635fd45b777a43079a93" FOREIGN KEY ("idProfissional") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "FK_af30f71f9bf51c20d3840f5f73a" FOREIGN KEY ("idAfericaoGestante") REFERENCES "afericoesGestante"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "FK_a989d78546c4c92a75030f9e57b" FOREIGN KEY ("idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "FK_197c88b7792ba2fd7216d4d6504" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "FK_d1ed3d975b2a075f5200fe39557" FOREIGN KEY ("idProfissional") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD CONSTRAINT "FK_77e4ac50f879d85bc90d34c7cea" FOREIGN KEY ("idAreaCobertura") REFERENCES "areaCobertura"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cidades" ADD CONSTRAINT "FK_f350a823445af81a3fe09a88cd5" FOREIGN KEY ("idEstado") REFERENCES "estados"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contatos" ADD CONSTRAINT "FK_364ffcb3c933087e548d11ea998" FOREIGN KEY ("idPessoa") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contatos" ADD CONSTRAINT "FK_386e6fd9d36dd12be8075350a58" FOREIGN KEY ("idResponsavel") REFERENCES "responsaveis"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_c4a4491685c1ccb1f2b57224221" FOREIGN KEY ("idPessoa") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_fe6ac807d8205db1c60abd2ac0f" FOREIGN KEY ("idResponsavel") REFERENCES "responsaveis"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_2ec665a2ed88e74ab3e84da3f06" FOREIGN KEY ("idCidade") REFERENCES "cidades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exames" ADD CONSTRAINT "FK_7bf98e7e612d97046f956c78d90" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD CONSTRAINT "FK_ccbf683639190838391a2047d47" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD CONSTRAINT "FK_4a999b64e4c581f5855875e1a71" FOREIGN KEY ("idBebe") REFERENCES "bebes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD CONSTRAINT "FK_bab4e996e61ba75b94735bd2dea" FOREIGN KEY ("idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" ADD CONSTRAINT "FK_52140c874ac3ab8f13366c071c0" FOREIGN KEY ("idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" ADD CONSTRAINT "FK_a85d8f2fa353aae051b8e6af1d6" FOREIGN KEY ("idBebe") REFERENCES "bebes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" ADD CONSTRAINT "FK_0fdca7f509d4325c331332d9837" FOREIGN KEY ("idAfericaoBebe") REFERENCES "afericoesBebes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" ADD CONSTRAINT "FK_cccd7af34794e992f8a24125dd7" FOREIGN KEY ("idProfissionais") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" DROP CONSTRAINT "FK_cccd7af34794e992f8a24125dd7"`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" DROP CONSTRAINT "FK_0fdca7f509d4325c331332d9837"`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" DROP CONSTRAINT "FK_a85d8f2fa353aae051b8e6af1d6"`);
        await queryRunner.query(`ALTER TABLE "visitaRecemNascido" DROP CONSTRAINT "FK_52140c874ac3ab8f13366c071c0"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP CONSTRAINT "FK_bab4e996e61ba75b94735bd2dea"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP CONSTRAINT "FK_4a999b64e4c581f5855875e1a71"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP CONSTRAINT "FK_ccbf683639190838391a2047d47"`);
        await queryRunner.query(`ALTER TABLE "exames" DROP CONSTRAINT "FK_7bf98e7e612d97046f956c78d90"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_2ec665a2ed88e74ab3e84da3f06"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_fe6ac807d8205db1c60abd2ac0f"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP CONSTRAINT "FK_c4a4491685c1ccb1f2b57224221"`);
        await queryRunner.query(`ALTER TABLE "contatos" DROP CONSTRAINT "FK_386e6fd9d36dd12be8075350a58"`);
        await queryRunner.query(`ALTER TABLE "contatos" DROP CONSTRAINT "FK_364ffcb3c933087e548d11ea998"`);
        await queryRunner.query(`ALTER TABLE "cidades" DROP CONSTRAINT "FK_f350a823445af81a3fe09a88cd5"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP CONSTRAINT "FK_77e4ac50f879d85bc90d34c7cea"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "FK_d1ed3d975b2a075f5200fe39557"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "FK_197c88b7792ba2fd7216d4d6504"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "FK_a989d78546c4c92a75030f9e57b"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "FK_af30f71f9bf51c20d3840f5f73a"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "FK_97b0493635fd45b777a43079a93"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "FK_52cfb62ef98cd012d176d7fa46f"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "FK_e5071a3dcca98ed5006c2cba34c"`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" DROP CONSTRAINT "FK_d6e6bd8a56b543d986f80d1902a"`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" DROP CONSTRAINT "FK_0b6fc12b539c1f5d10cecca9176"`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" DROP CONSTRAINT "FK_d8034b1478f5fa22932ae267cab"`);
        await queryRunner.query(`ALTER TABLE "consultasAbertura" DROP CONSTRAINT "FK_c06fe4220bc31e20b9d062c158b"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "FK_6c4a5500dfbc4d941da6885e4cf"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "FK_3a4ce6bcb3c0b621ec0cc9cb93c"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "FK_c57978982b4e0638aaea0e0fe2f"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "tipoPaciente"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "tipoPaciente" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP CONSTRAINT "UQ_0cdb0a19a284ab273d794bce3a5"`);
        await queryRunner.query(`ALTER TABLE "agendamentos" ALTER COLUMN "horaRetorno" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "agendamentos" ALTER COLUMN "dataRetorno" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "idadeGestacional"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "idadeGestacional" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "pressaoArterial"`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "pressaoArterial" character varying`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "idGestacao"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "dataExclusao"`);
        await queryRunner.query(`ALTER TABLE "bebes" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "gestacoes" DROP COLUMN "idadeGestacional"`);
        await queryRunner.query(`ALTER TABLE "gestacoes" DROP COLUMN "nivelRisco"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "idBebe"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "idGestacao"`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" DROP COLUMN "nome"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "alergias"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "tipoSanguineo"`);
        await queryRunner.query(`ALTER TABLE "pacientes" DROP COLUMN "hasResponsavel"`);
        await queryRunner.query(`ALTER TABLE "pessoas" DROP COLUMN "tipoPessoa"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP COLUMN "idCidade"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP COLUMN "idResponsavel"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP COLUMN "idPessoa"`);
        await queryRunner.query(`ALTER TABLE "enderecos" DROP COLUMN "titular"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP CONSTRAINT "UQ_77e4ac50f879d85bc90d34c7cea"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP COLUMN "idAreaCobertura"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP COLUMN "equipe"`);
        await queryRunner.query(`ALTER TABLE "profissionais" DROP COLUMN "cargo"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "idProfissional"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "idGestacao"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP CONSTRAINT "UQ_a989d78546c4c92a75030f9e57b"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "idAgendamento"`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" DROP COLUMN "prescricoes"`);
        await queryRunner.query(`ALTER TABLE "agendamentos" DROP COLUMN "dataExclusao"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "UQ_af30f71f9bf51c20d3840f5f73a"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "idAfericaoGestante"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "idProfissional"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP CONSTRAINT "UQ_52cfb62ef98cd012d176d7fa46f"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "idAgendamento"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "idGestacao"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "dataAlteracao"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "dataCriacao"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "observacoes"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "sintomas"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "status"`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" DROP COLUMN "nivelRisco"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "idProfissionais"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "idGestacao"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP CONSTRAINT "UQ_c57978982b4e0638aaea0e0fe2f"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "idAgendamento"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "recomendacoes"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "observacoes"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "vulnerabilidades"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "movimentosFetais"`);
        await queryRunner.query(`ALTER TABLE "visitas" DROP COLUMN "ultimaConsultaRealizada"`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "observacoes" text`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "gestacoes_idGestacao" integer`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "pessoas_idPessoa" integer`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD CONSTRAINT "REL_b50000f3706608bec4ef0c925c" UNIQUE ("pessoas_idPessoa")`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "primeiraConsulta" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "apgar" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "comprimentoNascimento" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD "pesoNascimento" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gestacoes" ADD "dataProvavelParto" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "gestacoes" ADD "dataUltimaMenstruacao" TIMESTAMP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "idadeGestacional" character varying`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "profissionais_idProfissional" integer`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "pacientes_idPaciente" integer`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "status" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "dataAlteracao" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD "dataCriacao" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "observacao" text`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "nivelRisco" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "examesId" integer`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD "responsavel" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "profissao" character varying`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "alergias" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "comorbidades" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "tipoSanguineo" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "telefone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "pessoas" ADD "email" character varying`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD "cidades_idCidade" integer`);
        await queryRunner.query(`ALTER TABLE "responsaveis" ADD "telefone" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD "observacao" text`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD "funcao" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD "equipes_idEquipe" integer`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "profissionais_idProfissional" integer`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "pacientes_idPaciente" integer`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "agendamentos_idAgendamento" integer`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "status" boolean NOT NULL`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "dataAlteracao" TIMESTAMP DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD "dataCriacao" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "historicoGestacional" text`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "consultas_id" integer`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "REL_7c46626609a2fa17bfc6f49d9d" UNIQUE ("consultas_id")`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "batimentosCardiacos" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD "alturaUterina" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "observacao" text`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "faseAcompanhamento" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "profissionais_idProfissionais" integer`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "pacientes_idPacientes" integer`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD "agendamentos_idAgendamento" integer`);
        await queryRunner.query(`DROP TABLE "visitaRecemNascido"`);
        await queryRunner.query(`DROP TABLE "afericoesBebes"`);
        await queryRunner.query(`DROP TABLE "contatos"`);
        await queryRunner.query(`DROP TABLE "areaCobertura"`);
        await queryRunner.query(`DROP TABLE "afericoesGestante"`);
        await queryRunner.query(`DROP TABLE "consultasAbertura"`);
        await queryRunner.query(`ALTER TABLE "exames" RENAME COLUMN "idGestacao" TO "pacientes_idPaciente"`);
        await queryRunner.query(`ALTER TABLE "cidades" RENAME COLUMN "idEstado" TO "estados_idEstado"`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD CONSTRAINT "FK_017442fdf85248269ab2e248ebc" FOREIGN KEY ("gestacoes_idGestacao") REFERENCES "gestacoes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bebes" ADD CONSTRAINT "FK_b50000f3706608bec4ef0c925c0" FOREIGN KEY ("pessoas_idPessoa") REFERENCES "pessoas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD CONSTRAINT "FK_fc0e9dfe46f90c7b86fd9645383" FOREIGN KEY ("profissionais_idProfissional") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vacinacoes" ADD CONSTRAINT "FK_9a16946211d04cc3ef1409e3074" FOREIGN KEY ("pacientes_idPaciente") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "exames" ADD CONSTRAINT "FK_5416bbb44a12e2b5f89a1826b47" FOREIGN KEY ("pacientes_idPaciente") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pacientes" ADD CONSTRAINT "FK_ca615f9bb29f30e88403e10d15d" FOREIGN KEY ("examesId") REFERENCES "exames"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "enderecos" ADD CONSTRAINT "FK_e5dc50dc3a19a78ba3d6aa8df59" FOREIGN KEY ("cidades_idCidade") REFERENCES "cidades"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cidades" ADD CONSTRAINT "FK_26fdc1287cd3546d3445ae61fab" FOREIGN KEY ("estados_idEstado") REFERENCES "estados"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "profissionais" ADD CONSTRAINT "FK_3c63dfaf4590b751af96d12f853" FOREIGN KEY ("equipes_idEquipe") REFERENCES "equipes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "FK_0c3e2ba4eac1a23f6b5013349a9" FOREIGN KEY ("profissionais_idProfissional") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "FK_136d00713f5cc9daef5a5df6cc8" FOREIGN KEY ("pacientes_idPaciente") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "avaliacoes_odonto" ADD CONSTRAINT "FK_a1f66b99dd471cf095b6803e0d7" FOREIGN KEY ("agendamentos_idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "consultasPreNatal" ADD CONSTRAINT "FK_7c46626609a2fa17bfc6f49d9dd" FOREIGN KEY ("consultas_id") REFERENCES "consultas"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "FK_b59117532f98fc4e4e3c558d365" FOREIGN KEY ("profissionais_idProfissionais") REFERENCES "profissionais"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "FK_6aae5fece0741ba004c922ebacb" FOREIGN KEY ("pacientes_idPacientes") REFERENCES "pacientes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visitas" ADD CONSTRAINT "FK_eb1658fc6adde4c67c2e6ac3a47" FOREIGN KEY ("agendamentos_idAgendamento") REFERENCES "agendamentos"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
